version: '3.8'

services:
  scraper:
    build: .
    container_name: scraper
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}
    networks:
      - diyanet_icerik

networks:
  diyanet_icerik:
    external: true
